language: node_js
node_js:
    - '4'
dist: trusty
before_install: |
    set -ev
    npm install -g npm
install: ./scripts/install-deps.sh
script: |
    set -ev
deploy:
    provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
