instrumentation:
    excludes:
        - "cli.js"
        - "index.js"
        - "lib/utils/*.js"
        - "lib/deployCommand.js"
        - "out/**"
        - "scripts/**"
        - "systest/**"
check:
    global:
        statements: 97
        branches: 95
        functions: 99
        lines: 97
