instrumentation:
    excludes:
        - "cli.js"
        - "index.js"
        - "lib/utils/*.js"
        - "lib/*Command.js"
        - "out/**"
        - "scripts/**"
        - "systest/**"
check:
    global:
        statements: 20
        branches: 20
        functions: 20
        lines: 20
