language: node_js
node_js:
    - '4'
    - '6'
matrix:
    include:
        - env: SYSTEST=embedded
        - env: SYSTEST=web
        - env: SYSTEST=hlf SYSTEST_HLF=hlf
          sudo: required
          services:
            - docker
        - env: SYSTEST=hlf SYSTEST_HLF=ibm
          sudo: required
          services:
            - docker
dist: trusty
before_install: |
    set -ev
    set -o pipefail
    npm install -g npm
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome*.deb
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    sudo apt-get update && sudo apt-get install cf-cli
install: |
    set -ev
    set -o pipefail
    npm install 2>&1 | tee
script: npm run script
after_success: |
    set -ev
    set -o pipefail
    npm config set registry https://registry.npmjs.org/
    npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    $(npm bin)/set-up-ssh --key "$encrypted_568b95f14ac3_key" \
                          --iv "$encrypted_568b95f14ac3_iv" \
                          --path-encrypted-key ".travis/github_deploy_key.enc"
deploy:
    provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
        all_branches: true
cache:
    directories:
        - $HOME/.npm
notifications:
    slack:
        secure: NX1j3tH5CQ4hsmMzpu6iJ48TWr+IgxJpUwVqOy1NOcm+W8v9G/DfB8B+NZdkmb38Lijh/7eMqbII7wwGtMdrJKV4/WDT5r7crSgI6ITLMcu7azAaULqhaBT+9yaptee/02SDo8sOLWuG1+t2YaWTaP4lGp5VcB836CKZfyk3SRFbKJQZPioN+ivkuiiAA2JMQMeOzV5fpVFEBSBG4qwqUxyTWIL6fWtEjvtmEOwfcCEhmJv7Q2jnO0L3OGHAkXh6XauwYLElhwU/xxNT27N/gca9hB4DlMZjsag74YjkG2U0lZ71eFXq/TLfhLyUcyDs2LMLmaTU0cGILz9sP4HXZWGSxXfAZz259t41yX8sngdpUraU4j0v0grHuq83pA+OAP+X+FYhzoWJ5NFOv5URj17h+U7p5k3Np1TqeTtoQwVFbXnwcuVGlzdGoN9BzqHDiw5SW/n7dXPMp8LAXj8HHy+L5j26OtVq7UL6XjHxMUuHS31bp5QdBqmS/u+PkWI1IsfcQKhK3ip5iYc7OSEuzeswQRySpS2Qw4OHaSzAfTfbF877w7WHjYN3uu3MejfJLqI/pSyRZTDzafc2tydfJMPuh7BXP7DtJlXKfLQdD9uCdzFIrpyZ/xgeuvN949cIZE8Ip0Dy/69/pgZslH5OpHSrRFnz4jOZQTh47ibqJaU=
