language: node_js
node_js:
    - '4'
    - '6'
matrix:
    include:
        - env: DOCS=full
        - env: SYSTEST=embedded
        - env: SYSTEST=web
        - env: SYSTEST=hlf SYSTEST_HLF=hlf
          sudo: required
          services:
            - docker
        - env: SYSTEST=hlf SYSTEST_HLF=ibm
          sudo: required
          services:
            - docker
dist: trusty
addons:
    apt:
        packages:
            - graphviz
before_install: |
    date
    set -ev
    set -o pipefail
    ./.travis/before-install.sh
    date
install: |
    date
    set -ev
    set -o pipefail
    ./.travis/install.sh
    date
script: ./.travis/script.sh
deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
cache: false
