language: node_js
node_js:
    - '4'
    - '6'
matrix:
    include:
        - env: DOCS=full
        - env: SYSTEST=embedded
        - env: SYSTEST=web
        - env: SYSTEST=hlf SYSTEST_HLF=hlf
          sudo: required
          services:
            - docker
        - env: SYSTEST=hlf SYSTEST_HLF=ibm
          sudo: required
          services:
            - docker
dist: trusty
addons:
    apt:
        packages:
            - graphviz
before_install: |
    date
    set -ev
    set -o pipefail
    ./.travis/should-run.sh
    npm install -g npm
    npm install -g @alrra/travis-scripts
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome*.deb
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    sudo apt-get update && sudo apt-get install cf-cli
    date
install: |
    date
    set -ev
    set -o pipefail
    npm install 2>&1 | tee
    date
script: ./.travis/script.sh
deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
cache: false
