language: go
go:
    - 1.7
before_install: |
    set -ev
    nvm install 4
    npm install -g npm
    npm config set @ibm:registry https://npm-registry.whitewater.ibm.com
    npm config set //npm-registry.whitewater.ibm.com/:_authToken ${NPM_TOKEN}
install: |
    set -ev
    npm install
    npm run prepublish
    go get $(go list ./... | grep -v -e /vendor/ -e /node_modules/)
    go get github.com/golang/lint/golint
script: |
    set -ev
    go vet $(go list ./... | grep -v -e /vendor/ -e /node_modules/)
    golint -set_exit_status $(ls *.go | grep -v mock)
    go test -v $(go list ./... | grep -v -e /vendor/ -e /node_modules/)
deploy:
    provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
