instrumentation:
    excludes:
        - "out/**"
        - "scripts/**"
        - "integration-test/**"
check:
    global:
        statements: 100
        branches: 95
        functions: 100
        lines: 100
